### ISSUE TITLE
Compliment

### ISSUE THREAD

**Issue by delanick** [EddyVerbruggen/nativescript-keyboard-toolbar#1]
@EddyVerbruggen This is your best yet bud, awesome work! I've been wishing for something like this for ages! Can't wait to use it!

Thanks you!!

**Comment by EddyVerbruggen** [comment]
Thank you, that compliment is very much appreciated! Also: https://twitter.com/eddyverbruggen/status/1073501341639680000

**Comment by delanick** [comment]
@EddyVerbruggen Awesome! :D
